DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS groups_members;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    name        text not null default '',
    nonce       bigint not null default 0,
    id          uuid unique primary key DEFAULT extensions.uuid_generate_v4(),
    address     text not null UNIQUE
);

CREATE TABLE groups (
    id          bigint primary key generated by default as identity,
    name        text not null default '',
    description text not null
);

CREATE TABLE groups_members (
    id          bigint primary key generated by default as identity,
    user_id     uuid references public.users(id) not null,
    group_id    bigint references public.groups(id) not null
);

CREATE TABLE activity (
    id          bigint primary key generated by default as identity,
    group_id    bigint references public.groups(id) not null,
    name        text not null,
    total       float8 not null,
    payer       uuid references public.users(id) not null,
    creator     text
);

INSERT INTO public.users (name, address) values ('foo', 'bar');